# build the gateway binary
FROM golang:1.10.0 AS builder
LABEL stage=gateway-intermediate
WORKDIR /go/src/{{ .Root }}/{{ .Name }}
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/gateway ./cmd/gateway

# copy the gateway binary from builder stage; run the gateway binary
FROM alpine:latest AS runner
WORKDIR /bin
COPY --from=builder /go/src/{{ .Root }}/{{ .Name }}/bin/gateway .
ENTRYPOINT ["gateway"]